### PR TITLE
✨(UI): Adding UI Components

### PR DESCRIPTION
**Pull request by WesleyPachaiTuks**
Added structure for UI Components. Will complete full functionality and additional components in following commits.

### CODE REVIEW

**Review by u20437863-James-Butler — COMMENTED** [review]
Will that empty file be used for something?

**Comment by WesleyPachaiTuks** [comment]
> Will that empty file be used for something?

Yes, I will be added the styling for the html in there.

**Comment by u20437863-James-Butler** [comment]
Perfect

**Review by u20437863-James-Butler — APPROVED** [review]
Looks fine

**Pull request merged**
