### PR TITLE
✨ (api): add mock data for Authorization

### PR DESCRIPTION
**Pull request by Kuda214**

### CODE REVIEW

**Comment by Ray-net** [comment]
Please make sure you have all the meta tags then do the PR again

**Comment by Ray-net** [comment]
The rest looks good just all the tags and data that is required for all the tests to run

**Comment by Kuda214** [comment]
> Please make sure you have all the meta tags then do the PR again

The milestone check is failing, and yet l have added that tag

**Comment by Alexander-Muendesi** [comment]
@Kuda214 ignore the failed milestone check. it only runs on initial PR

**Review by Ray-net — APPROVED** [review]
Nothing seems out of place and all tests are cleared except milestone.

**Pull request merged**
