### PR TITLE
🤡(hosting): Mock API for status page

### PR DESCRIPTION
**Pull request by takumuguti**
created the mock API required for the hosting status page.

### CODE REVIEW

**Comment by arneschreuder** [comment]
How did you generate that library? `api/hosting/api/shared/data-access`. I am not really sure what that error is?

**Comment by MuziwandileTNdlovu** [comment]
> Could I please gain clarification on what this error means: image

it looks like it added an extra ../ to your file meaning it cant be found maybe you manually deleted a directory and it never recognised the is one less directory to traverse

**Comment by takumuguti** [comment]
> How did you generate that library? `api/hosting/api/shared/data-access`. I am not really sure what that error is?

I use the Nx Console in vs code, for the generator I used @nrwl/nest:library

**Comment by arneschreuder** [comment]
Maybe the easiest solution is to just chuck this away and redo it? Since this only has skeletal elements in it?

**Comment by takumuguti** [comment]
> > > Could I please gain clarification on what this error means: image
> > 
> > 
> > it looks like it added an extra ../ to your file meaning it cant be found maybe you manually deleted a directory and it never recognised the is one less directory to traverse
> 
> Thats why I asked how they generated the lib, since if they generated it using nx console, that should not be an issue.

I think I understand why the errors has occurred, the directory I used for generation of the data-access was api/hosting/api/shared/entities/ which I later changed to just api/hosting/api/shared/.

**Review by arneschreuder — APPROVED** [review]

**Comment by arneschreuder** [comment]
Shipit

**Pull request merged**
