### PR TITLE
✨(UI): Receives Student Number and Choices

### PR DESCRIPTION
**Pull request by WesleyPachaiTuks**
When user submits, a variable with their student number and permission choices is created which can be passed to the API.

### CODE REVIEW

**Comment by arneschreuder** [comment]
Reminder that this PR has to be in at 23:59:59.

**Review by u20437863-James-Butler — DISMISSED** [review]
If it passes I'll merge

**Review by u20437863-James-Butler — APPROVED** [review]
Hopefully that change fixes it

**Comment by arneschreuder** [comment]
Please close this PR and make from a feature branch. Also, this is a pretty big PR, only fixes to the release branch will be allowed, not entire features. I will let it slide for now, but please...

**Comment by WesleyPachaiTuks** [comment]
> Please close this PR and make from a feature branch. Also, this is a pretty big PR, only fixes to the release branch will be allowed, not entire features. I will let it slide for now, but please...

I'm unsure how to go about migrating my changes to a feature branch since I made them in the develop branch of my fork. Could you give me some guidance on this?

**Pull request closed without merging**
