### PR TITLE
:art: rebuilt shorts UI lib and added report-menu component to it

### PR DESCRIPTION
**Pull request by DYL-WF**
Completely rebuilt lib and added reports component

### CODE REVIEW

**Comment by KearonF** [comment]
@DYL-WF, there seems to be an issue with the way the report menu componennt is being exported, causing the testing to fail. see below:

libs/client/shorts/feature/src/lib/report-menu/report-menu.component.ts:8:14 - error NG3001: Unsupported private class ReportMenuComponent. This class is visible to consumers via ClientShortsFeatureModule -> ReportMenuComponent, but is not exported from the top-level library entrypoint.

**Comment by MatthewGotte** [comment]
@KearonF we are trying to fix it now, it seems like the component was not generated correctly

**Review by KearonF — APPROVED** [review]

**Review by MatthewGotte — APPROVED** [review]

**Review by rayden96 — APPROVED** [review]

**Comment by arneschreuder** [comment]
Wait, why was this merged in? The project is not generated correctly?

**Comment by arneschreuder** [comment]
Client libs should not be buildable. I dont know why there is an ng-package.json and a browserlistrc etc?

**Comment by arneschreuder** [comment]
Please see the example in libs/client/example/feature and fix in future PR

**Pull request merged**
