### PR TITLE
(UI): Fixes to routing Module

### PR DESCRIPTION
**Pull request by WesleyPachaiTuks**
Fixes to allow the routing module for UP Integration to be used. Needs to be used by the Student Profile feature.

### CODE REVIEW

**Review by u20437863-James-Butler — APPROVED** [review]
It looks like this fixes it, but we'll need Cara to double check that it functions

**Comment by u20437863-James-Butler** [comment]
@caaaramia Can you please check if the issue you had is resolved by this PR

**Review by brettdup — APPROVED** [review]

**Comment by u20437863-James-Butler** [comment]
@arneschreuder Can we merge this PR, or should we wait for your review as well?

**Review by u20437863-James-Butler — APPROVED** [review]
Looks good

**Comment by u20437863-James-Butler** [comment]
@WesleyPachaiTuks I think Brett may be on a plane currently, so we may need to get another team member to review in his stead

**Review by brettdup — APPROVED** [review]

**Comment by u20437863-James-Butler** [comment]
I'll merge now as to allow the other team to make the fix on their side.

**Pull request merged**
