### PR TITLE
✨ (CQRS): add a query to request access entities

### PR DESCRIPTION
**Pull request by FaraiQC**

### CODE REVIEW

**Comment by FaraiQC** [comment]
Good day @arneschreuder 
Do you know why I might be getting this test error. When I run "yarn nx run-many --target=lint --all" to test on visual studio code, all the tests are successful ( >  NX   Successfully ran target lint for 93 projects (8m))

**Comment by arulagrawal** [comment]
> Good day @arneschreuder Do you know why I might be getting this test error. When I run "yarn nx run-many --target=lint --all" to test on visual studio code, all the tests are successful ( > NX Successfully ran target lint for 93 projects (8m))

Its the unit test that's failing, not the lint test

**Comment by arneschreuder** [comment]
So this service: RequestAccessService needs the QueryBus to be provided in the testing module. Like this:


```ts
const module: TestingModule = await Test.createTestingModule({
      imports: [CqrsModule],
      providers: [....],
    }).compile();
```

**Comment by FaraiQC** [comment]
> So this service: RequestAccessService needs the QueryBus to be provided in the testing module. Like this:
> 
> ```ts
> const module: TestingModule = await Test.createTestingModule({
>       imports: [CqrsModule],
>       providers: [....],
>     }).compile();
> ```


> So this service: RequestAccessService needs the QueryBus to be provided in the testing module. Like this:
> 
> ```ts
> const module: TestingModule = await Test.createTestingModule({
>       imports: [CqrsModule],
>       providers: [....],
>     }).compile();
> ```

Thank you. Let me add more unit tests

**Review by arulagrawal — APPROVED** [review]

**Pull request merged**
