### PR TITLE
🎨🔥🚑 👽️(storage): Cleaned up the flow from api-resolver to repository

### PR DESCRIPTION
**Pull request by LarisaBothaTuks**
Major changes affecting the api and repository.
Handling of promise returns and awaiting on functions in order for data to flow correctly from the repository through the service to the resolver.

### CODE REVIEW

**Comment by LarisaBothaTuks** [comment]
I discovered a bug in the config. I plan on fixing it soon for now to allow everyone that is using firebase to test sufficiently I re added it to the repository. 
@OmolemoMashigo please see the storage.service.ts
@MuziwandileTNdlovu please clean up the upload function

**Comment by LarisaBothaTuks** [comment]
This PR is of very high priority @lindzik @ZoeLiebenberg

**Review by lindzik — APPROVED** [review]
No tampering to .gitignore file, naming conventions check out. Made from a feature branch. Approve merging

**Comment by ZoeLiebenberg** [comment]
Milestone test failed but @LarisaBothaTuks did put it into the sprint 2 milestone and @lindzik attempted to remove it and readd it

**Comment by Alexander-Muendesi** [comment]
Just for future reference the milestone check runs once on initial PR hence why it did not update. We could not get it to run past that

**Pull request merged**
