### PR TITLE
👩‍💻🔥💡(storage) : Added access functions to firebase repository

### PR DESCRIPTION
**Pull request by LarisaBothaTuks**
Provided an enum of firebase folder names and a function to assist the hosting team upload database dumps from an internal or external directory.

Added comments to improve developer's understanding of the repository and to explain how to use it.

This function also asists our feature since multer saves to a folder within the nest structure.

### CODE REVIEW

**Comment by JurassicRegz** [comment]
Please make sure to assign a CI/CD team member when making PRs and also make sure to add all the relevant meta tags, projects and milestones.

**Comment by LarisaBothaTuks** [comment]
I tried rerunning the tests because it fails me on the merit of labels,milestones and priority which isn't supposed to since I have all 3.

**Comment by Alexander-Muendesi** [comment]
@LarisaBothaTuks . It fails because you need the following: Priority, status, scope, type, role, milestone labels

**Comment by LarisaBothaTuks** [comment]
Thank you noted. I am still not sure what the difference is so excuse my mistake. I do have milestone's and priority that is why I am confused. I did read the test errors.

**Comment by Alexander-Muendesi** [comment]
@LarisaBothaTuks  sorry for the inconvenience. Just one moment for my team to add scop: repository to the list of our scopes. we missed that. Otherwise you are right it should pass

**Comment by Alexander-Muendesi** [comment]
@LarisaBothaTuks  we updated the list. can you just remove scope: repository label and then add it again. That should rerun it and pass the meta test

**Comment by Alexander-Muendesi** [comment]
This is strange. Let me have a second look again. we did add scope: repository to list

**Comment by LarisaBothaTuks** [comment]
@Alexander-Muendesi It seems to be failing not only on labels.

**Review by lindzik — APPROVED** [review]
Changes have been reviewed and no issues from my side. Some meta tests failed but we got the merge go ahead from the CICD feature team

**Comment by Alexander-Muendesi** [comment]
I think it might be a space issue. I see its written scope: repository and in our list its scope:repository. Otherwise everything else in your PR is fine

**Comment by Alexander-Muendesi** [comment]
Finally. Apologies again for the inconvenience. We will make sure to match the exact formatting of the labels ASAP

**Comment by Alexander-Muendesi** [comment]
@LarisaBothaTuks  @lindzik . Okay so the people who made that script are saying for the last 2 to pass just close this PR and make a new one with all the milestones and labels added when you are making it and those last 2 should pass. I think some changes might have to be made on our side to avoid you having to do a new PR in future

**Comment by JurassicRegz** [comment]
The final two tests remain as failed due to the fact that they only run on a new PR and not an existing one (that is why the other 2 Meta tests have passed as they account for this change within the PR that has already been opened). There are no more conflicts and it is not an error on your side so our apologize we will find a fix for this.

**Comment by ZoeLiebenberg** [comment]
Passed all checks (except for a few that did not cause conflicts). Merged after a discussion between all parties

**Pull request merged**
