### PR TITLE
🎨 Feature/notifications Corrected file structure

### PR DESCRIPTION
**Pull request by fffrikkie**
Corrected file structure issue mentioned here #521.
Includes desktop and mobile UI for notifications feature.
No navbar.

### CODE REVIEW

**Review by arneschreuder — APPROVED** [review]
Perfect.

**Comment by arneschreuder** [comment]
You still need to add routing. But this can be done in a future PR

**Comment by fffrikkie** [comment]
@arneschreuder How do I add the routing?

**Comment by arneschreuder** [comment]
Shipit

**Comment by fffrikkie** [comment]
Does the Nx console extension have a way to add the routing, since the link mentions doing it via the CLI? @arneschreuder

**Pull request merged**
