### PR TITLE
🎨🔥🚑 👽️(storage): Cleaned up the flow from api-resolver to repository  #3

### PR DESCRIPTION
**Pull request by LarisaBothaTuks**
Major changes affecting the api and repository.
Handling of promise returns and awaiting on functions in order for data to flow correctly from the repository through the service to the resolver.
Includes api upload function.

### CODE REVIEW

**Comment by LarisaBothaTuks** [comment]
These are the changes I meant to establish in the first PR of the same title. Sorry to everyone that needed these changes I meant for this to already been changed by Friday already.

**Review by TimovdMerwe-18 — APPROVED** [review]
Good job! Thanks Larisa

**Comment by LarisaBothaTuks** [comment]
@arneschreuder did I do the config right this time?

**Review by TimovdMerwe-18 — APPROVED** [review]

**Review by lindzik — APPROVED** [review]
Tests ran successfully. Naming conventions check out. Approve merging.

**Pull request merged**
