### PR TITLE
✅ (Shorts-DB): Integration Tests

### PR DESCRIPTION
**Pull request by KearonF**

### CODE REVIEW

**Comment by KearonF** [comment]
Build is somehow being affected by other modules (Student Explore and Company Profile APIs)

**Comment by DYL-WF** [comment]
did you comment the problem APIs? @KearonF

**Comment by KearonF** [comment]
Will try that now

**Comment by KearonF** [comment]
The problem API's are already commented out it seems

**Comment by KearonF** [comment]
Integration Tests failing because of no connection to db in CI pipeline

**Comment by KearonF** [comment]
Commented out Integration tests as they are not running in the CI pipeline, but they are running locally. As per below screenshot: 
image

**Pull request merged**
