### PR TITLE
🚑️(repo): fix yarn.lock issues

### PR DESCRIPTION
**Pull request by arulagrawal**
attempt at fixing the pipeline breakage by reverting yarn.lock to a known state

### CODE REVIEW

**Comment by arneschreuder** [comment]
Push another commit, should pass the meta checks

**Comment by arneschreuder** [comment]
Lets wait for tests, then we check

**Review by arneschreuder — APPROVED** [review]

**Comment by arneschreuder** [comment]
Shipit

**Comment by arulagrawal** [comment]
This lockfile is taken from https://github.com/COS-301/graduates/commit/63e4ebdeda74d93dd61aac5cd6be6e63db4fd614. Is this the right place?

**Comment by arneschreuder** [comment]
Maybe to make sure. Delete the yarn.lock, regenerate and push

**Comment by arulagrawal** [comment]
I tried `yarn generate-lock-entry > yarn.lock` but could not get a working configuration that way @arneschreuder

**Comment by arneschreuder** [comment]
No man, just rm -rf yarn.lock and yarn install. Commit and push

**Comment by arulagrawal** [comment]
@arneschreuder It doesn't work with a newly generated yarn.lock (tested locally). I can push that here if you'd like but I'm pretty sure it'd just fail here too

**Comment by arneschreuder** [comment]
Sure, lets see what the output is. that means some package broke the pipeline

**Comment by arulagrawal** [comment]
`rm -f yarn.lock`
`yarn install`
`yarn nx reset`
`yarn nx run-many --target=lint --all`
```
yarn run v1.22.18
$ /home/arul/code/graduates/node_modules/.bin/nx run-many --target=lint --all

Unexpected error:
TypeError: Cannot read properties of undefined (reading 'hashCommand')
    at /home/arul/code/graduates/node_modules/@nrwl/linter/src/executors/eslint/hasher.js:11:32
    at Generator.next (<anonymous>)
    at /home/arul/code/graduates/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/arul/code/graduates/node_modules/tslib/tslib.js:113:16)
    at run (/home/arul/code/graduates/node_modules/@nrwl/linter/src/executors/eslint/hasher.js:7:34)
    at TasksSchedule.<anonymous> (/home/arul/code/graduates/node_modules/nx/src/tasks-runner/tasks-schedule.js:117:19)
    at Generator.next (<anonymous>)
    at /home/arul/code/graduates/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by arneschreuder** [comment]
Ok give me a sec

**Comment by arneschreuder** [comment]
Ok, something is broken with the linter. I will have a look tonight

**Comment by arulagrawal** [comment]
Fixed instead by #512

**Pull request closed without merging**
