### PR TITLE
✨(company-representative): Mock silo

### PR DESCRIPTION
**Pull request by Siphesihle05**

### CODE REVIEW

**Comment by arneschreuder** [comment]
Please update your branch and resolve conflicts

**Comment by Zenthon** [comment]
@arneschreuder How do we handle conflicts?

**Comment by arneschreuder** [comment]
Hi @Siphesihle05 let me help you get your PR in, you are so close. Ok, so here is what I need you to do:

1. Use nx console extension in VSCode and nx move the library for me. Please use lowercase notation. `company-representative`. The library's path should be:  `libs/api/company-representative/api/feature/`, NOT `libs/api/CompanyRepresentative/api/feature/`
2. Then, I see your branch is outdated again. Just update again and we can merge.

**Comment by arneschreuder** [comment]
> @arneschreuder Sir, how do we fix lint errors?

@Zenthon please run `nx lint api-CompanyRepresentative-api-feature`, you will see, there are tests that fail.

**Comment by Zenthon** [comment]
Thank you sir

**Comment by arneschreuder** [comment]
I would perhaps suggest that you close this PR and redo this. Copy out the resolvers and the files that you made by hand, regenerate the lib correctly and then put your code back.

Then make the PR from your feature branch, not develop on your fork, makes it a bit simpler to manage develop it things go wrong. 


If you can get this to work, cool. But maybe it is easier to just start from scratch.

**Pull request closed without merging**
