### PR TITLE
Authorization Service Layer 

### PR DESCRIPTION
**Pull request by Khotso-Bore**
The service layer and it's accompanying Queries and handler functions have been completed

### CODE REVIEW

**Comment by Vhulenda88** [comment]
Check this for naming conventions
https://github.com/COS-301/graduates/discussions/3#discussioncomment-2481491

**Comment by Khotso-Bore** [comment]
> 

wll do

**Comment by Khotso-Bore** [comment]
Where does one add metas?

**Comment by Khotso-Bore** [comment]
- Please add meta such as labels, milestone, associated project and linked issue to the PR.
- EVERY PR MUST GO HAND IN HAND WITH AN ISSUE THAT IT IS LINKED TO. PLEASE HELP DRIVE THIS CULTURE.
- Please name the PR title the same as the others (using the notation <emoji>(scope): Subject line
-
followingg that

**Comment by Vhulenda88** [comment]
Did you change your yarn.lock file yourself 

> * Please add meta such as labels, milestone, associated project and linked issue to the PR.
> * EVERY PR MUST GO HAND IN HAND WITH AN ISSUE THAT IT IS LINKED TO. PLEASE HELP DRIVE THIS CULTURE.
> * Please name the PR title the same as the others (using the notation (scope): Subject line
> 
> followingg that

On the side bar under reviewers

**Pull request closed without merging**
