### PR TITLE
💄(ui): Added Filter UI Component  #386

### PR DESCRIPTION
**Pull request by MattReed-ZA**
Filter UI Component for Student Explore Feature. Uses mock data. Issue #386

### CODE REVIEW

**Review by Daniel-J-Burgess — CHANGES_REQUESTED** [review]
The following are listed as unknown
mat-card,mat-card-title,mat-card-content,mat-card-actions and mat-icon
it also states that the export of name 'matMenu' cannot be found.
Please have a look to see whether you are missing an import somewhere.

**Review by Daniel-J-Burgess — CHANGES_REQUESTED** [review]
Please import UsersService in users.module.ts and list it as a provider.
Then in api-authentication-api-feature.module.ts it should be User module as a provider not UsersResolver

**Review by Daniel-J-Burgess — APPROVED** [review]

**Comment by Daniel-J-Burgess** [comment]
I believe everything is in order and that it can be merged in.

**Review by jonahgasura — APPROVED** [review]
No issues with this PR. It will now be merged.

**Comment by arneschreuder** [comment]
@Alexander-Muendesi why did CI/CD not trigger on this PR?

**Comment by arneschreuder** [comment]
Is it because this PR was from their develop branch?

**Comment by priyo5** [comment]
@arneschreuder on my side I see checks have run

**Comment by JurassicRegz** [comment]
@arneschreuder Same here, just below this message:

> No issues with this PR. It will now be merged.

It shows the checks have passed.

**Comment by arneschreuder** [comment]
O nvm, sorry, I see it now.

**Pull request merged**
