### PR TITLE
🤡 ✨ (ui): Add/Implement NGXS, Mock api and search functionality

### PR DESCRIPTION
**Pull request by Thivesshj**
### Made a Mock API
**to run:**
- > change directory to lib/client/company/explore-feature/src/lib/mock-api and run,
- > json-server --watch data.json

### Implemented NGXS
all relevant files in the store folder of my library.
**actions:** creates classes GetCompanyList and setSearch
**service:** implements fetchCompanyList and this is also where i will change the _URL_ call the implemented the company explore API in due time
**State:** i store the retrieved company list also a search parameter to be implemented when performing searches.
also changed my landing page to pass the data to the relevant components namely content and cards

### Search Functionality
seachbar changed to add a search parameter to the route.
this will be called in company-explore component, which It will use it to set the
search state variable and filter the results.
also changed the search to not be case sensitive
### Fixed Unit tests
 some injection  and typecasting errors... 😩 

//added a rick roll? 👀

### CODE REVIEW

**Review by RobynHancock — COMMENTED** [review]
All good

**Review by RobynHancock — COMMENTED** [review]
Good

**Review by RobynHancock — APPROVED** [review]
Good

**Review by L3m0nRoCk — COMMENTED** [review]
looks good!

**Pull request merged**
