### PR TITLE
🔥 (Shorts-API): Added Testing, new API Queries and Commands

### PR DESCRIPTION
**Pull request by BenjaminOsmers**
- Added Unit Testing
- Created fetchShortById, fetchShortsByUser, fetchShortsByTag
- Created createShort

### CODE REVIEW

**Comment by ChrisMagerat** [comment]
In libs/api/shorts/service/feature/src/lib/ApiShortsService.service.spec.ts on line 99 there should be 3 arguments but only 2 is given.

**Comment by BenjaminOsmers** [comment]
@ChrisMagerat I'm not sure why it is failing now?

**Comment by ChrisMagerat** [comment]
It is failing the test api-shorts-repository-data-access:test.

**Comment by ChrisMagerat** [comment]
It seems like it can't access the api repository.

**Comment by BenjaminOsmers** [comment]
I think I found the issue, fixing it now

**Comment by Alexander-Muendesi** [comment]
your unit test failed. line 357

**Comment by arneschreuder** [comment]
> In libs/api/shorts/service/feature/src/lib/ApiShortsService.service.spec.ts on line 99 there should be 3 arguments but only 2 is given.
> 
> userId Was not given.

Also, the naming convention is wrong. Should be this-is-the-filename.scope.spec.ts

**Comment by KearonF** [comment]
The mock promise in findByID in ApiShortsRepository.repository.spec.ts should be resolved to null before testing if it resolves to null. It is still resolving to ShortMock when that section (from line 56) runs

**Comment by KearonF** [comment]
Remember to refactor changed filenames in imports and dependencies as well

**Review by KearonF — APPROVED** [review]

**Review by DYL-WF — APPROVED** [review]

**Pull request merged**
