### PR TITLE
Revert "✅ (request-for-access):wrote unit tests for the data access functions"

### PR DESCRIPTION
**Pull request by LiamBurgess18015001**
Reverts COS-301/graduates#1054

### CODE REVIEW

**Comment by LiamBurgess18015001** [comment]
Something may be accidentally breaking our code. Need to review.

**Review by dylan2894 — CHANGES_REQUESTED** [review]
Retest

**Comment by JurassicRegz** [comment]
Milestone check is good. Just running off a stale test.

**Review by LiamBurgess18015001 — COMMENTED** [review]
Need to change milestone

**Review by dylan2894 — APPROVED** [review]

**Pull request merged**
