### PR TITLE
🐛 ✅  (repo) add tests

### PR DESCRIPTION
**Pull request by Ray-net**

### CODE REVIEW

**Comment by Ray-net** [comment]
Cant access database. Cant run test. Any suggestions would be nice.

**Comment by Ray-net** [comment]
Tests function on local database. Not on github docker.

**Review by Vhulenda88 — COMMENTED** [review]
Are you still working on this or are the unit tests failing because of the same problem you had with github docker port ?

**Comment by Ray-net** [comment]
fixed and all tests pasted

**Review by Vhulenda88 — APPROVED** [review]

**Pull request merged**
