### PR TITLE
🗃️ (db): CRUD finalised, Firebase support added, File storage added

### PR DESCRIPTION
**Pull request by David-Roodt**

### CODE REVIEW

**Comment by David-Roodt** [comment]
@DanieldeNobrega. I will talk to DB engineers about changes then reopen. The changes we need for our stuff broke some of their stuff.

**Comment by David-Roodt** [comment]
I made changes to the DB schema that we need. It breaks other groups code but I already sent them fixes on Discord

**Review by DanieldeNobrega — DISMISSED** [review]
All files look good.

**Review by DanieldeNobrega — APPROVED** [review]
All looks good.

**Review by DanieldeNobrega — APPROVED** [review]
All files look good.

**Comment by David-Roodt** [comment]
DB needed changes on a few tables. Everyone who's code was effected was notified. The tables were changed to have 2 primary keys instead of 1. This is to allow users to add multiple emails, degrees and social medias to the same account.

**Pull request merged**
