### PR TITLE
🎨 🔥 (ui): Add/export angular-material modules to shared UI

### PR DESCRIPTION
**Pull request by Thivesshj**
Added angular-material modules to shared Ui Module to be imported/exported and used by other UI engineers. 

removed company-explore-materials.module

### CODE REVIEW

**Comment by Alexander-Muendesi** [comment]
Please use feature branches when merging into develop.  @Thivesshj @L3m0nRoCk 

You should avoid using that ---> Thivesshj:develop

**Comment by Thivesshj** [comment]
@arneschreuder Hello. Sorry to disturb.

with regards to the previous comment on this PR:

> Please use feature branches when merging into develop. @Thivesshj @L3m0nRoCk
> 
> You should avoid using that ---> Thivesshj:develop

Do we have a company-explore feature branch?or must i make the branch on my fork?
thank you.

**Comment by Alexander-Muendesi** [comment]
@Thivesshj If all your checks pass and you are reviewed you can merge this one its fine. But for future PRs just make them through feature branches. From what I saw regarding his comments in PRs, Mr Arne just recommends feature branches when merging cause it makes merging easier in some cases. As for your question I think people do that on their forks but confirm with someone who has already been following that feature branch convention, I am not a 100% sure of that

**Comment by arneschreuder** [comment]
Hi @Thivesshj. What @Alexander-Muendesi said is correct. Making the PRs from feature branches are easier, especially when things go wrong. You make the feature branch on your on fork using `git checkout -b feature/whatever` and then push using `git push origin feature/whatever`. Make the PR then from this forked feature branch to upstream develop.

**Pull request closed without merging**
