### PR TITLE
🎨(storage): Simplified testing

### PR DESCRIPTION
**Pull request by LarisaBothaTuks**
Added boolean return types to functions to simplify the testing process
And created a hash for the filename since we decided not to use the multer library for uploads

### CODE REVIEW

**Comment by priyo5** [comment]
Milestone check can be ignored
Please add a status label

**Comment by LarisaBothaTuks** [comment]
I have no idea whats up with the lint test, any suggestion would be appreciated.

**Comment by JurassicRegz** [comment]
> Milestone check can be ignored Please add a status label

Please also assign a Project board to this PR.

**Comment by lindzik** [comment]
@arneschreuder could you please assist us with this lint error. The lint test is the only one failing, with the following error.

lint error

**Comment by arneschreuder** [comment]
This is the same issue that broke the pipeline. To check:

* Checkout develop
* Make sure you have latest stuff
* rm -rf node_modules
* yarn
* nx clear-cache
* nx run-many --target=lint --all --skip-nx-cache

If this fails for develop, the pipeline broke again and needs fixing. If it passes, then the issues is on this branch and we can sort out.

**Comment by Alexander-Muendesi** [comment]
@arneschreuder if it is broken potentially then it would have to be some PRs after around 4PM yesterday because we did try implement that functionality where the tests are run without cache after a merge on develop and the pipeline was fine when the test completed. the only issue we had was that cypress was complaining about something we needed to fix so we took out that functionality till we sort it out

**Comment by LarisaBothaTuks** [comment]
Lint tests ran successfully on develop branch. What is my next step?

**Comment by arneschreuder** [comment]
I just tested develop on my end and it is still working. So it is not that.

**Comment by arneschreuder** [comment]
I just tested develop on my end and it is still working. So it is not that.

**Comment by arneschreuder** [comment]
@LarisaBothaTuks maybe try the following. Checkout your branch again. rm -rf node_modules, yarn again and run the tests. If it doesn't work, maybe try chucking away the yarn.lock?

**Comment by LarisaBothaTuks** [comment]
I did do that just now just omitted the node_modules command since it told me that no such thing exist. The lint test ran successfully on my side. It should work now I will wait for the checks to finish here. Thank you for the assistance.

**Review by lindzik — APPROVED** [review]
Test ran successfully. No tampering to .gitignore file, naming conventions check out. Made from a feature branch. Approve merging

**Pull request merged**
